version: "3.0"
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_SEARCH_VERSION}
        environment:
            - xpack.security.enabled=false
            - discovery.type=single-node
        ports:
            - ${ELASTIC_SEARCH_PORT}:9200
        volumes:
            - ./elasticsearch_data:/usr/share/elasticsearch/data
    
    kibana:
        image: docker.elastic.co/kibana/kibana:${ELASTIC_SEARCH_VERSION}
        environment:
            - ELASTICSEARCH_HOSTS=http://${ELASTIC_SEARCH_ADDRESS}:${ELASTIC_SEARCH_PORT}
        depends_on:
            - elasticsearch
        ports:
            - ${KIBANA_PORT}:5601
        volumes:
            - ./kibana_data:/usr/share/kibana/data
